### PR TITLE
Unity 2020 LTS support

### PR DESCRIPTION
**Pull request by mjducharme**
Added support for Unity 2020 LTS. Additional changes required for the recent Unity 2021 LTS.

### CODE REVIEW

**Comment by mjducharme** [comment]
I would also note that this commit doesn't back out the neobits floating point precision commit bug as the pull request done by @landonth was prior to that, so reverting that back in your repo will be an extra step, @lmontoute

**Comment by mjducharme** [comment]
Also @lmontoute notice that I reverted back some changes that @landonth made as I found they were not ultimately necessary in getting this working, and I wanted to reduce the scope of this so that the bare minimum changes were required.

**Comment by lmontoute** [comment]
@mjducharme can you enable edits from maintainers on this PR? More info if you need:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

With a few additional changes, I think I have this completed for Unity 2021.

**Comment by mjducharme** [comment]
@lmontoute "Allow edits by maintainers" is already enabled

**Comment by mjducharme** [comment]
@lmontoute And yes, this version almost works with 2021 from the little testing I did, the only issue was a cylinder collider that was deprecated. Once I fixed that it seemed to work fine. At that time however it wasn't LTS and so I wasn't looking at using it.

**Comment by lmontoute** [comment]
Can't seem to push to this PR (access denied), so opening a new one at #51

**Pull request closed without merging**
